# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Quote')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.User')),
            ],
        ),
    ]
